### ISSUE TITLE
プレイリスト表示中(背景が黄色のFragmentを表示中)に、backを押せることがわかりにくい

### ISSUE THREAD

**Issue by anolivetree** [kkkkan/Android-YouTube-Background-Player#14]
・閉じるためのボタンを置く
・fragmentが下からanimationして出てくる
など、stackに積まれたことが分かるようなUIになっていると嬉しいです。

**Comment by kkkkan** [comment]
修正しました。
とりあえず、今回は閉じるボタンをプレイリストタイトルの横に設置しましたが、何となく動きが格好悪い気がするのでfragmentを出すとき戻すときのアニメーションも近いうちに足すかもしれないです。

 f06ea73bc113bfef5df53cb7f481b296583a291a
