### ISSUE TITLE
keystore.propertiesファイルが無いと、ビルドに失敗する

### ISSUE THREAD

**Issue by anolivetree** [kkkkan/Android-YouTube-Background-Player#3]
keystore.propertiesがないと、gradleがエラーを出してビルドに失敗します。

**Comment by kkkkan** [comment]
ご指摘ありがとうございます。

46c1ea133e47031e8ea4de24bfec98e397b9368f
で修正いたしました。
（ダミーのkeystore.propertiesを追加いたしました。）
