### ISSUE TITLE
keystore.propertiesの先頭にbyte order markが入っている

### ISSUE THREAD

**Issue by anolivetree** [kkkkan/Android-YouTube-Background-Player#4]
ファイルの先頭に、0xef, 0xbb, 0xbfのbyte order markが入っているぽいです。
そのため、linuxではstorePassword=を認識できなくなりました。
可能ならbyte order markを消していただけますか。

**Comment by kkkkan** [comment]
5bde0720481f7896e156caaa190aaeb9ed2fb159

で消したつもりなのですが、自分の環境だと元からstorePassword=を認識できていたためちゃんと修正できているか確認が取れませんでした。
linuxでうまく認識できるかご確認していただければと思います。

**Comment by anolivetree** [comment]
バイナリエディタで確認しましたが、byte order markは無くなったようです。

**Comment by kkkkan** [comment]
ご確認ありがとうございました。
