### ISSUE TITLE
同じビデオを何度も再生すると、履歴が多量に残る

### ISSUE THREAD

**Issue by anolivetree** [kkkkan/Android-YouTube-Background-Player#8]
同じビデオの履歴が続く時は、一つにしてもらえると嬉しいです。

**Comment by kkkkan** [comment]
9d24562abb019dee79f33645bf9cba7b05fca545

こちらのコミットで、直前に見たビデオと同じビデオを再生したときは履歴に残さないようにしました。

**Comment by anolivetree** [comment]
ありがとうございます。

瑣末なことですが、createIfNotMatchWithTopVideoのコメントで、MethodをMezzodとtypoしています。

**Comment by kkkkan** [comment]
ご指摘ありがとうございます。気づきませんでした…。
恥ずかしいです。直しました。
